dashboard/urls.py
from django.contrib import admin
from django.urls import path
from dashboard.views import UserNotesView, UserAddNotesView, UserSaveNotesView, UserLogoutView, NoteDeleteView
from django.conf import settings
from django.conf.urls.static import static


app_name = 'notes'


urlpatterns = [
    path('notes_user/', UserNotesView.as_view(), name='note'),
    path('notes_add/', UserAddNotesView.as_view(), name='add'),
    path('save_note/', UserSaveNotesView.as_view(), name='keep'),
    path('logout_user/', UserLogoutView.as_view(), name='logout'),
    path('notes_delete/', NoteDeleteView.as_view(), name='delete'),

]



to_do/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls', namespace='users')),
    path('notes/', include('dashboard.urls', namespace='notes')),
]




user/urls.py
from django.contrib import admin
from django.urls import path
from user.views import RegistrationUserView, MainUserView, LoginUserView
from django.conf import settings
from django.conf.urls.static import static


app_name = 'users'


urlpatterns = [
    path('', MainUserView.as_view(), name='main'),
    path('register/', RegistrationUserView.as_view(), name='reg'),
    path('login/', LoginUserView.as_view(), name='log'),

]



dashboard/models.py
from django.db import models
from user.models import CustomUser


class Note(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(to=CustomUser, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user}'



user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    pass










dashboard/forms.py
from django import forms
from dashboard.models import Note


class AddNoteForm(forms.Form):
    title = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Введите название вашей заметки'}))
    content = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Введите вашу заметку'}))

    class Meta:
        model = Note
        fields = ['title', 'content']

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from user.models import CustomUser


class UserRegistrationForm(UserCreationForm):
    username = forms.CharField(label='Username', max_length=100)
    first_name = forms.CharField(label='Firstname', max_length=100)
    last_name = forms.CharField(label='Lastname', max_length=100)
    email = forms.CharField(label='Email', max_length=100)
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(label='Username', max_length=100)
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ('username', 'password')



dashboard/views.py
from django.contrib.auth import login
from django.urls import reverse
from django.views import View
from dashboard.forms import AddNoteForm
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth import logout
from dashboard.models import Note
from django.shortcuts import get_object_or_404
from django.views import View
from django.http import JsonResponse


class UserNotesView(View):
    template_name = 'dashboard/notes.html'

    def get(self, request):

        return render(request, self.template_name)


class UserAddNotesView(View):
    template_name = 'dashboard/add_note.html'

    def get(self, request, *args, **kwargs):
        form = AddNoteForm()
        return render(request, self.template_name, {'form': form})

    # def post(self, request, *args, **kwargs):
    #     form = AddNoteForm(request.POST)
    #     if form.is_valid():
    #         note = form.save(commit=False)
    #         note.user = request.user
    #         note.save()
    #         return HttpResponseRedirect(reverse('notes:note'))
    #     else:
    #         return render(request, 'add_note.html', {'form': form})
    def post(self, request, *args, **kwargs):
        form = AddNoteForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            content = form.cleaned_data['content']
            note = Note.objects.create(title=title, content=content, user=request.user)
            return HttpResponseRedirect(reverse('notes:keep'))
        else:
            return render(request, 'add_note.html', {'form': form})


class UserSaveNotesView(View):
    template_name = 'dashboard/save_notes.html'

    def get(self, request):
        notes = Note.objects.filter(user=request.user)
        return render(request, self.template_name, {'result_notes_get': notes})


class UserLogoutView(View):

    def get(self, request):
        logout(request)
        return HttpResponseRedirect(reverse('users:log'))


class NoteDeleteView(View):

    def post(self, request):
        note_id = request.POST.get('note_id') #получаем через post запрос при нажатии на кнопку id
        notes = get_object_or_404(Note, id=note_id) #теперь с помощью этого id мы получаем обьект информации в этой модели Note
        user = request.user #получаем текущего юзера
        if notes.user == user: #сравниваем что эта запись пренадлежит этому юзеру
            notes.delete() #если это так тогда удаляем запись

        return HttpResponseRedirect(reverse('notes:keep'))




user/views.py
from django.contrib import auth
from django.contrib.auth import login
from django.urls import reverse
from django.views import View
from user.forms import UserRegistrationForm, UserLoginForm
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.contrib.auth import login, authenticate


class MainUserView(View):
    template_name = 'dashboard/notes.html'
    template_name_2 = 'user/test.html'

    def get(self, request):
        if request.user.is_authenticated:
            return render(request, self.template_name)
        else:
            return render(request, self.template_name_2)


class RegistrationUserView(View):
    template_name = 'user/register.html'

    def get(self, request):
        form = UserRegistrationForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.save()
            login(request, user)
            return HttpResponseRedirect(reverse('notes:note'))
        else:
            print(form.errors)
        return render(request, self.template_name, {'form': form})


class LoginUserView(View):
    template_name = 'user/login.html'

    def get(self, request):
        form = UserLoginForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = auth.authenticate(username=username, password=password)
            if user:
                login(request, user)
                return HttpResponseRedirect(reverse('notes:note'))
            else:
                print(form.errors)
        return render(request, self.template_name, {'form': form})




dashboard/templates/dashboard/add_note.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Notes</title>
    <link rel="stylesheet" href="{% static 'vendor/css/add_notes.css' %}">
</head>
<body>
    <form action="{% url 'notes:add' %}" method="post" id="addNotesForm">
        {% csrf_token %}
        {{ form.title }}
        {{ form.content }}

        <input type="submit" value="Add Note">
    </form>
    <a href="{% url 'notes:keep' %}" class="add-notes-button">My Notes</a>
</body>
</html>

dashboard/templates/dashboard/notes.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'vendor/css/notes.css/' %}"> <!-- Замените путем к вашему CSS-файлу -->
    <title>MyNotes</title>
</head>
<body>
    <div class="container">
        <h2>Your Notes!!!</h2>
        <p class="my-note"></p>
        <a href="{% url 'notes:keep' %}" class="add-notes-button">My Notes</a>
        <a href="{% url 'notes:add' %}" class="btn btn-primary">Add Note</a>
        <a href="{% url 'notes:logout' %}" class="btn btn-danger">Logout</a>
    </div>
</body>
</html>

dashboard/templates/dashboard/save_notes.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Notes</title>
    <link rel="stylesheet" href="{% static 'vendor/css/save_note.css' %}">
</head>
<body>
<h1>Your Notes!!!</h1>
<a href="{% url 'notes:add' %}" class="add-notes-button">Add Notes</a>
<a href="{% url 'notes:logout' %}" class="btn btn-danger logout-btn">Logout</a>
<!-- Список для отображения добавленных заметок -->
<ul id="noteList">
    {% for note in result_notes_get %}
    <li class="note">
        <div class="note-number">{{ forloop.counter }}</div>
        <div class="note-content">
            <p>{{ note.title }}</p>
            <p>{{ note.content }}</p>
        </div>
        <form action="{% url 'notes:delete' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="note_id" value="{{ note.id }}">
    <button type="submit">Remove</button>
        </form>
    </li>
    {% endfor %}
</ul>
</body>
</html>

user/templates/user/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'vendor/css/login.css/' %}"> <!-- Замените путем к вашему CSS-файлу -->
    <title>Login Page</title>
</head>
<body>
    <div class="container">
        <h1>Login</h1>
        <form action="{% url 'users:log' %}" method="post"> <!-- Замените  на ваш путь к обработчику авторизации -->
            {% csrf_token %}

            <label for="{{ form.username.id_for_label }}">Username:</label>
            {{ form.username }}

            <label for="{{ form.password.id_for_label }}">Password:</label>
            {{ form.password }}


            <button type="submit" class="btn btn-primary">Login</button>
        </form>
    </div>
</body>
</html>

user/templates/user/register.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'vendor/css/register.css/' %}"> <!-- Замените путем к вашему CSS-файлу -->
    <title>Registration Page</title>
</head>
<body>
    <div class="container">
        <h1>Register</h1>
        <form action="{% url 'users:reg' %}" method="post"> <!-- Замените 'register_user' на ваш путь к обработчику регистрации -->
            {% csrf_token %}

            <label for="{{ form.username.id_for_label }}">Username:</label>
            {{ form.username }}

            <label for="{{ form.first_name.id_for_label }}">First Name:</label>
            {{ form.first_name }}

            <label for="{{ form.last_name.id_for_label }}">Last Name:</label>
            {{ form.last_name }}

            <label for="{{ form.email.id_for_label }}">Email:</label>
            {{ form.email }}

            <label for="{{ form.password1.id_for_label }}">Password:</label>
            {{ form.password1 }}

            <label for="{{ form.password2.id_for_label }}">Confirm Password:</label>
            {{ form.password2 }}

            <button type="submit" class="btn btn-primary">Register</button>
        </form>
    </div>
</body>
</html>

user/templates/user/test.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'vendor/css/test.css/' %}"> <!-- Замените путем к вашему CSS-файлу -->
    <title>Registration Page</title>
</head>
<body>
    <div class="container">
        <h1>Welcome to Our Site!</h1>
        <p>Register now to get started!</p>
        <a href="{% url 'users:reg' %}" class="btn btn-primary">Register</a> <!-- Замените 'registration' на ваш путь к регистрации -->
        <a href="{% url 'users:log' %}" class="btn btn-primary">Authorization</a>
    </div>
</body>
</html>